query getCart {
  cart {
    checkoutUrl
    grandTotal
    items {
      id
      quantity
      price
      discountTotal
      taxTotal
      product {
        id
        name
        currency
      }
    }
  }
}

mutation addToCart($productId: ID!, $quantity: Int!, $variantId: ID!) {
  addCartItem(
    input: { productId: $productId, quantity: $quantity, variantId: $variantId }
  ) {
    checkoutUrl
    grandTotal
    items {
      id
      quantity
      price
      discountTotal
      taxTotal
      product {
        id
        name
        currency
      }
    }
  }
}

mutation removeCartItem($itemId: String!) {
  deleteCartItem(itemId: $itemId) {
    checkoutUrl
    grandTotal
    items {
      id
      quantity
      price
      discountTotal
      taxTotal
      product {
        id
        name
        currency
        options {
          id
          name
        }
      }
    }
  }
}
